// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MlhJXtZkJ-S-f3KrwEu8ZVAcFXMgK2I',
    appId: '1:847918291952:web:2809b37dd1e3bfb6d09b35',
    messagingSenderId: '847918291952',
    projectId: 'thetazinee',
    authDomain: 'thetazinee.firebaseapp.com',
    storageBucket: 'thetazinee.firebasestorage.app',
    measurementId: 'G-YNP68EWJH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YEUvw2vc1Fx54ne9tqZ1j5w0pYm1T2A',
    appId: '1:847918291952:android:0b96a7dda3a71d88d09b35',
    messagingSenderId: '847918291952',
    projectId: 'thetazinee',
    storageBucket: 'thetazinee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJMr6Mwzk_UDUtLdoGLroc1QVUWT8mk4',
    appId: '1:847918291952:ios:5fb3574cfa9a3f7ed09b35',
    messagingSenderId: '847918291952',
    projectId: 'thetazinee',
    storageBucket: 'thetazinee.firebasestorage.app',
    iosBundleId: 'com.coffeeshop.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJMr6Mwzk_UDUtLdoGLroc1QVUWT8mk4',
    appId: '1:847918291952:ios:5fb3574cfa9a3f7ed09b35',
    messagingSenderId: '847918291952',
    projectId: 'thetazinee',
    storageBucket: 'thetazinee.firebasestorage.app',
    iosBundleId: 'com.coffeeshop.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0MlhJXtZkJ-S-f3KrwEu8ZVAcFXMgK2I',
    appId: '1:847918291952:web:c26a10d3d0f3e582d09b35',
    messagingSenderId: '847918291952',
    projectId: 'thetazinee',
    authDomain: 'thetazinee.firebaseapp.com',
    storageBucket: 'thetazinee.firebasestorage.app',
    measurementId: 'G-VFBRT895H4',
  );
}
